export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_SUCCESS2 = 'FETCH_DATA_SUCCESS2'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'
export const FETCH_DATA_sTART = 'FETCH_DATA_sTART'

export const FETCH_DATA_SUCCESS_BY_ADDRESS = 'FETCH_DATA_SUCCESS_BY_ADDRESS'
export const FETCH_DATA_SUCCESS_BY_ADDRESS2 = 'FETCH_DATA_SUCCESS_BY_ADDRESS2'
export const FETCH_DATA_BY_ADDRESS_FAIL = 'FETCH_DATA_BY_ADDRESS_FAIL'
export const FETCH_DATA_BY_ADDRESS_sTART = 'FETCH_DATA_BY_ADDRESS_sTART'