export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_SUCCESS2 = 'FETCH_DATA_SUCCESS2'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'
export const FETCH_DATA_sTART = 'FETCH_DATA_sTART'